package com.smarthome.socket.wsservice.stub;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "SmartHomeTcpService", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/")
public interface SmartHomeTcpService {

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteByEntity", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.DeleteByEntity")
	@ResponseWrapper(localName = "deleteByEntityResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.DeleteByEntityResponse")
	public boolean deleteByEntity(
			@WebParam(name = "arg0", targetNamespace = "") Push arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.smarthome.socket.wsservice.stub.AppVO
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveOrUpdateDeviceByEasyLogin", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.SaveOrUpdateDeviceByEasyLogin")
	@ResponseWrapper(localName = "saveOrUpdateDeviceByEasyLoginResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.SaveOrUpdateDeviceByEasyLoginResponse")
	public AppVO saveOrUpdateDeviceByEasyLogin(
			@WebParam(name = "arg0", targetNamespace = "") AppLoginVO arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<com.smarthome.socket.wsservice.stub.Push>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "listPushByClientId", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.ListPushByClientId")
	@ResponseWrapper(localName = "listPushByClientIdResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.ListPushByClientIdResponse")
	public List<Push> listPushByClientId(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "queryCronTimeUpdate", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.QueryCronTimeUpdate")
	@ResponseWrapper(localName = "queryCronTimeUpdateResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.QueryCronTimeUpdateResponse")
	public String queryCronTimeUpdate();

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "insertPushFinish", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.InsertPushFinish")
	@ResponseWrapper(localName = "insertPushFinishResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.InsertPushFinishResponse")
	public boolean insertPushFinish(
			@WebParam(name = "arg0", targetNamespace = "") Long arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns java.util.List<com.smarthome.socket.wsservice.stub.Push>
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "listPush", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.ListPush")
	@ResponseWrapper(localName = "listPushResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.ListPushResponse")
	public List<Push> listPush(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateDeviceStatusByMac", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.UpdateDeviceStatusByMac")
	@ResponseWrapper(localName = "updateDeviceStatusByMacResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.UpdateDeviceStatusByMacResponse")
	public void updateDeviceStatusByMac(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deleteById", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.DeleteById")
	@ResponseWrapper(localName = "deleteByIdResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.DeleteByIdResponse")
	public boolean deleteById(
			@WebParam(name = "arg0", targetNamespace = "") Long arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveClientLog", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.SaveClientLog")
	@ResponseWrapper(localName = "saveClientLogResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.SaveClientLogResponse")
	public boolean saveClientLog(
			@WebParam(name = "arg0", targetNamespace = "") ClientLog arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns com.smarthome.socket.wsservice.stub.Push
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "findById", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.FindById")
	@ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.FindByIdResponse")
	public Push findById(
			@WebParam(name = "arg0", targetNamespace = "") Long arg0);

	/**
	 * 
	 * @param arg0
	 * @return returns boolean
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "deviceOutLine", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.DeviceOutLine")
	@ResponseWrapper(localName = "deviceOutLineResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.DeviceOutLineResponse")
	public boolean deviceOutLine(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg0
	 */
	@WebMethod
	@RequestWrapper(localName = "updateDeviceStatusForAll", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.UpdateDeviceStatusForAll")
	@ResponseWrapper(localName = "updateDeviceStatusForAllResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.UpdateDeviceStatusForAllResponse")
	public void updateDeviceStatusForAll(
			@WebParam(name = "arg0", targetNamespace = "") String arg0);

	/**
	 * 
	 * @param arg1
	 * @param arg0
	 * @return returns com.smarthome.socket.wsservice.stub.PushMapConvertor
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "listPushByClientIDForMap", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.ListPushByClientIDForMap")
	@ResponseWrapper(localName = "listPushByClientIDForMapResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.ListPushByClientIDForMapResponse")
	public PushMapConvertor listPushByClientIDForMap(
			@WebParam(name = "arg0", targetNamespace = "") String arg0,
			@WebParam(name = "arg1", targetNamespace = "") String arg1);

	/**
	 * 
	 * @param arg0
	 * @return returns com.smarthome.socket.wsservice.stub.AppVO
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "saveOrUpdateDevice", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.SaveOrUpdateDevice")
	@ResponseWrapper(localName = "saveOrUpdateDeviceResponse", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/", className = "com.smarthome.socket.wsservice.stub.SaveOrUpdateDeviceResponse")
	public AppVO saveOrUpdateDevice(
			@WebParam(name = "arg0", targetNamespace = "") AppLoginVO arg0);

}
