
package com.biencloud.smarthome.web.wsclient.stub;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.4.6
 * 2014-07-13T13:58:54.216+08:00
 * Generated source version: 2.4.6
 */

@WebFault(name = "Exception", targetNamespace = "http://service.cxfservice.smarthome.biencloud.com/")
public class Exception_Exception extends java.lang.Exception {
    
    private com.biencloud.smarthome.web.wsclient.stub.Exception exception;

    public Exception_Exception() {
        super();
    }
    
    public Exception_Exception(String message) {
        super(message);
    }
    
    public Exception_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public Exception_Exception(String message, com.biencloud.smarthome.web.wsclient.stub.Exception exception) {
        super(message);
        this.exception = exception;
    }

    public Exception_Exception(String message, com.biencloud.smarthome.web.wsclient.stub.Exception exception, Throwable cause) {
        super(message, cause);
        this.exception = exception;
    }

    public com.biencloud.smarthome.web.wsclient.stub.Exception getFaultInfo() {
        return this.exception;
    }
}
